-- ═══════════════════════════════════════════════════════════════════════════
-- formation_slot_positions.sql — seeded reference: Opta slot -> position
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Spec: md/GOLD_LAYER.md §4.6.0, §6 Step 6.
--
-- GENERATED, not hand-written. The mean (x, y) of every event by the player
-- occupying each (team_formation, formation_position) was computed over every
-- starting XI in the database, and the five rules of §4.6.0 applied to it:
--
--   1. slot 1                      -> GK
--   2. slots 2 and 3               -> RB / LB. BY SLOT NUMBER, not by measured
--      y: slot 2 is the right side (mean y ~ 11, 839 right-footed to 13),
--      slot 3 the left (mean y ~ 57). Low y is the RIGHT flank.
--   3. centre backs                -> slots 5,6 in a back four; slots 4,5,6 in
--      a back three or five. The count comes from the starting XI itself
--      (COUNT(position = 'DEF')).
--   4. everything else             -> y < 24 RW, y > 44 LW, else central;
--      central with x >= 62 is ST, otherwise midfield.
--   5. within the central midfield -> lowest mean x is DM and highest is AM,
--      but ONLY where the gap to the next slot is >= 5 m. A flat double pivot
--      is two CMs, not a DM and a CM.
--
-- Rules 1-4 fix position_group and are not judgement calls. Rule 5 refines
-- DM/CM/AM only, and every one of those maps to position_group 'MID' -- so it
-- can never move a player between percentile peer sets (§4.6.14).
--
-- To regenerate after new formations appear, re-run the mean-(x,y) query in
-- §6 Step 6 and re-apply these rules. Validation assertions live in §9.5 G14.
--
-- Idempotent: ON CONFLICT DO NOTHING. Correct a single slot by UPDATE; do not
-- edit the build SQL.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS gold.formation_slot_positions (
    team_formation     VARCHAR(15) NOT NULL,
    formation_position SMALLINT    NOT NULL CHECK (formation_position BETWEEN 1 AND 11),
    position           VARCHAR(3)  NOT NULL
        CHECK (position IN ('GK','CB','RB','LB','DM','CM','AM','RW','LW','ST')),
    position_group     VARCHAR(3)  NOT NULL
        CHECK (position_group IN ('GK','CB','RB','LB','MID','W','ST')),
    PRIMARY KEY (team_formation, formation_position)
);

INSERT INTO gold.formation_slot_positions
    (team_formation, formation_position, position, position_group)
VALUES
    ('8', 1, 'GK', 'GK'),
    ('8', 2, 'RB', 'RB'),
    ('8', 3, 'LB', 'LB'),
    ('8', 4, 'CM', 'MID'),
    ('8', 5, 'CB', 'CB'),
    ('8', 6, 'CB', 'CB'),
    ('8', 7, 'RW', 'W'),
    ('8', 8, 'CM', 'MID'),
    ('8', 9, 'ST', 'ST'),
    ('8', 10, 'AM', 'MID'),
    ('8', 11, 'LW', 'W'),
    ('2', 1, 'GK', 'GK'),
    ('2', 2, 'RB', 'RB'),
    ('2', 3, 'LB', 'LB'),
    ('2', 4, 'CM', 'MID'),
    ('2', 5, 'CB', 'CB'),
    ('2', 6, 'CB', 'CB'),
    ('2', 7, 'RW', 'W'),
    ('2', 8, 'CM', 'MID'),
    ('2', 9, 'ST', 'ST'),
    ('2', 10, 'ST', 'ST'),
    ('2', 11, 'LW', 'W'),
    ('4', 1, 'GK', 'GK'),
    ('4', 2, 'RB', 'RB'),
    ('4', 3, 'LB', 'LB'),
    ('4', 4, 'DM', 'MID'),
    ('4', 5, 'CB', 'CB'),
    ('4', 6, 'CB', 'CB'),
    ('4', 7, 'CM', 'MID'),
    ('4', 8, 'CM', 'MID'),
    ('4', 9, 'ST', 'ST'),
    ('4', 10, 'RW', 'W'),
    ('4', 11, 'LW', 'W'),
    ('7', 1, 'GK', 'GK'),
    ('7', 2, 'RB', 'RB'),
    ('7', 3, 'LB', 'LB'),
    ('7', 4, 'DM', 'MID'),
    ('7', 5, 'CB', 'CB'),
    ('7', 6, 'CB', 'CB'),
    ('7', 7, 'RW', 'W'),
    ('7', 8, 'CM', 'MID'),
    ('7', 9, 'ST', 'ST'),
    ('7', 10, 'CM', 'MID'),
    ('7', 11, 'LW', 'W'),
    ('10', 1, 'GK', 'GK'),
    ('10', 2, 'RB', 'RB'),
    ('10', 3, 'LB', 'LB'),
    ('10', 4, 'CB', 'CB'),
    ('10', 5, 'CB', 'CB'),
    ('10', 6, 'CB', 'CB'),
    ('10', 7, 'CM', 'MID'),
    ('10', 8, 'DM', 'MID'),
    ('10', 9, 'ST', 'ST'),
    ('10', 10, 'ST', 'ST'),
    ('10', 11, 'CM', 'MID'),
    ('13', 1, 'GK', 'GK'),
    ('13', 2, 'RB', 'RB'),
    ('13', 3, 'LB', 'LB'),
    ('13', 4, 'CB', 'CB'),
    ('13', 5, 'CB', 'CB'),
    ('13', 6, 'CB', 'CB'),
    ('13', 7, 'CM', 'MID'),
    ('13', 8, 'CM', 'MID'),
    ('13', 9, 'ST', 'ST'),
    ('13', 10, 'RW', 'W'),
    ('13', 11, 'LW', 'W'),
    ('12', 1, 'GK', 'GK'),
    ('12', 2, 'RB', 'RB'),
    ('12', 3, 'LB', 'LB'),
    ('12', 4, 'CB', 'CB'),
    ('12', 5, 'CB', 'CB'),
    ('12', 6, 'CB', 'CB'),
    ('12', 7, 'CM', 'MID'),
    ('12', 8, 'CM', 'MID'),
    ('12', 9, 'ST', 'ST'),
    ('12', 10, 'ST', 'ST'),
    ('12', 11, 'DM', 'MID'),
    ('11', 1, 'GK', 'GK'),
    ('11', 2, 'RB', 'RB'),
    ('11', 3, 'LB', 'LB'),
    ('11', 4, 'CB', 'CB'),
    ('11', 5, 'CB', 'CB'),
    ('11', 6, 'CB', 'CB'),
    ('11', 7, 'RW', 'W'),
    ('11', 8, 'CM', 'MID'),
    ('11', 9, 'ST', 'ST'),
    ('11', 10, 'CM', 'MID'),
    ('11', 11, 'LW', 'W'),
    ('17', 1, 'GK', 'GK'),
    ('17', 2, 'RB', 'RB'),
    ('17', 3, 'LB', 'LB'),
    ('17', 4, 'CB', 'CB'),
    ('17', 5, 'CB', 'CB'),
    ('17', 6, 'CB', 'CB'),
    ('17', 7, 'CM', 'MID'),
    ('17', 8, 'CM', 'MID'),
    ('17', 9, 'ST', 'ST'),
    ('17', 10, 'RW', 'W'),
    ('17', 11, 'LW', 'W'),
    ('6', 1, 'GK', 'GK'),
    ('6', 2, 'RB', 'RB'),
    ('6', 3, 'LB', 'LB'),
    ('6', 4, 'CM', 'MID'),
    ('6', 5, 'CB', 'CB'),
    ('6', 6, 'CB', 'CB'),
    ('6', 7, 'RW', 'W'),
    ('6', 8, 'CM', 'MID'),
    ('6', 9, 'ST', 'ST'),
    ('6', 10, 'ST', 'ST'),
    ('6', 11, 'LW', 'W'),
    ('5', 1, 'GK', 'GK'),
    ('5', 2, 'RB', 'RB'),
    ('5', 3, 'LB', 'LB'),
    ('5', 4, 'CM', 'MID'),
    ('5', 5, 'CB', 'CB'),
    ('5', 6, 'CB', 'CB'),
    ('5', 7, 'RW', 'W'),
    ('5', 8, 'CM', 'MID'),
    ('5', 9, 'AM', 'MID'),
    ('5', 10, 'CM', 'MID'),
    ('5', 11, 'LW', 'W'),
    ('18', 1, 'GK', 'GK'),
    ('18', 2, 'RB', 'RB'),
    ('18', 3, 'LB', 'LB'),
    ('18', 4, 'CB', 'CB'),
    ('18', 5, 'CB', 'CB'),
    ('18', 6, 'CB', 'CB'),
    ('18', 7, 'CM', 'MID'),
    ('18', 8, 'CM', 'MID'),
    ('18', 9, 'AM', 'MID'),
    ('18', 10, 'ST', 'ST'),
    ('18', 11, 'ST', 'ST'),
    ('19', 1, 'GK', 'GK'),
    ('19', 2, 'RB', 'RB'),
    ('19', 3, 'LB', 'LB'),
    ('19', 4, 'CB', 'CB'),
    ('19', 5, 'CB', 'CB'),
    ('19', 6, 'CB', 'CB'),
    ('19', 7, 'CM', 'MID'),
    ('19', 8, 'DM', 'MID'),
    ('19', 9, 'ST', 'ST'),
    ('19', 10, 'ST', 'ST'),
    ('19', 11, 'CM', 'MID'),
    ('23', 1, 'GK', 'GK'),
    ('23', 2, 'RB', 'RB'),
    ('23', 3, 'LB', 'LB'),
    ('23', 4, 'DM', 'MID'),
    ('23', 5, 'CB', 'CB'),
    ('23', 6, 'CB', 'CB'),
    ('23', 7, 'RW', 'W'),
    ('23', 8, 'AM', 'MID'),
    ('23', 9, 'ST', 'ST'),
    ('23', 10, 'ST', 'ST'),
    ('23', 11, 'LW', 'W'),
    ('3', 1, 'GK', 'GK'),
    ('3', 2, 'RB', 'RB'),
    ('3', 3, 'LB', 'LB'),
    ('3', 4, 'DM', 'MID'),
    ('3', 5, 'CB', 'CB'),
    ('3', 6, 'CB', 'CB'),
    ('3', 7, 'RW', 'W'),
    ('3', 8, 'AM', 'MID'),
    ('3', 9, 'ST', 'ST'),
    ('3', 10, 'ST', 'ST'),
    ('3', 11, 'LW', 'W'),
    ('9', 1, 'GK', 'GK'),
    ('9', 2, 'RB', 'RB'),
    ('9', 3, 'LB', 'LB'),
    ('9', 4, 'DM', 'MID'),
    ('9', 5, 'CB', 'CB'),
    ('9', 6, 'CB', 'CB'),
    ('9', 7, 'LW', 'W'),
    ('9', 8, 'RW', 'W'),
    ('9', 9, 'ST', 'ST'),
    ('9', 10, 'ST', 'ST'),
    ('9', 11, 'AM', 'MID'),
    ('15', 1, 'GK', 'GK'),
    ('15', 2, 'RB', 'RB'),
    ('15', 3, 'LB', 'LB'),
    ('15', 4, 'DM', 'MID'),
    ('15', 5, 'CB', 'CB'),
    ('15', 6, 'CB', 'CB'),
    ('15', 7, 'RW', 'W'),
    ('15', 8, 'AM', 'MID'),
    ('15', 9, 'LW', 'W'),
    ('15', 10, 'ST', 'ST'),
    ('15', 11, 'LW', 'W'),
    ('16', 1, 'GK', 'GK'),
    ('16', 2, 'RB', 'RB'),
    ('16', 3, 'LB', 'LB'),
    ('16', 4, 'CB', 'CB'),
    ('16', 5, 'CB', 'CB'),
    ('16', 6, 'CB', 'CB'),
    ('16', 7, 'RW', 'W'),
    ('16', 8, 'CM', 'MID'),
    ('16', 9, 'ST', 'ST'),
    ('16', 10, 'ST', 'ST'),
    ('16', 11, 'CM', 'MID'),
    ('21', 1, 'GK', 'GK'),
    ('21', 2, 'RB', 'RB'),
    ('21', 3, 'LB', 'LB'),
    ('21', 4, 'DM', 'MID'),
    ('21', 5, 'CB', 'CB'),
    ('21', 6, 'CB', 'CB'),
    ('21', 7, 'RW', 'W'),
    ('21', 8, 'CM', 'MID'),
    ('21', 9, 'ST', 'ST'),
    ('21', 10, 'CM', 'MID'),
    ('21', 11, 'LW', 'W')
ON CONFLICT (team_formation, formation_position) DO NOTHING;
